/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2018-06-19 06:41:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class setptpoligon_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tlds/fn.tld", Long.valueOf(1384075604000L));
    _jspx_dependants.put("/backglobal.jsp", Long.valueOf(1527385603000L));
    _jspx_dependants.put("/global.jsp", Long.valueOf(1529327782000L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1384075546000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery-ui.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/global.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/combox.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery-ui-timepicker-addon.css\" />\r\n");
      out.write("<script type=text/javascript src=\"js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery.form.min.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/common.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/globalize.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/globalize.culture.de-DE.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/combox.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery-ui-timepicker-addon.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery.ui.datepicker-zh-CN.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery-ui-timepicker-zh-CN.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=text/javascript src=\"modules/modules.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/Tdrag.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/button/button.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/labelinput/labelinput.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/dialog/dialog.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/messagebox.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/SimpleGrid.css\" />\r\n");
      out.write("<script type=text/javascript src=\"js/SimpleGrid.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=text/javascript src=\"js/amapinit.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var g_unitType=[\r\n");
      out.write("\t\"托儿所\",\"小学\",\"九年一贯制学校\",\"中学\",\"初中\",\r\n");
      out.write("\t\"普通高中\",\"中等专业学校\",\"高等院校\",\"特殊学校\",\"综合医院\",\r\n");
      out.write("\t\"专科医院\",\"卫生服务中心\",\"青少年活动中心\",\"敬老院\",\"老年人活动站\",\r\n");
      out.write("\t\"党政机关\",\"公安局\",\"街道办事处\",\"街道派出所\",\"社区居委会\",\r\n");
      out.write("\t\"社区服务中心\",\"社区文娱中心\",\"体育活动中心\",\"社区警务室\",\"社区服务站\",\r\n");
      out.write("\t\"社区文化站\",\"社区健身场\",\"影剧院\",\"图书馆\",\"书报刊门市部\",\r\n");
      out.write("\t\"综合超市\",\"市场\",\"社区肉菜市场\",\"邮政支局\",\"邮政所\",\r\n");
      out.write("\t\"电信分局\",\"电信母局\",\"电信模块局\",\"微波站\",\"宽带IP\",\r\n");
      out.write("\t\"有线电视次中心\",\"工商所\",\"税务所\",\"文物古迹\",\"广场\",\r\n");
      out.write("\t\"公共厕所\",\"再生资源回收站\",\"环卫机构\",\"环卫工人休息站\",\"危险品仓库\",\r\n");
      out.write("\t\"消防站\",\"变电站\",\"开闭所\",\"天然气门站\",\"燃气调压站\",\r\n");
      out.write("\t\"储配站\",\"瓶装供应站\",\"供热设施\",\"调压站\",\"给水泵站\",\r\n");
      out.write("\t\"排水泵站\",\"自来水厂\",\"垃圾收集站\",\"垃圾转运站\",\"污水处理厂\",\r\n");
      out.write("\t\"加油加气站\",\"公共停车场\",\"车辆清洗场\",\"巡警队\",\"交通中队\",\r\n");
      out.write("\t\"货运站场\",\"公交首末站\",\"公交综合站场\",\"长途客运站\",\"铁路站场\",\r\n");
      out.write("\t\"火车客运站\",\"轨道交通站场\",\"轻轨站\",\"港口\",\"游艇码头\",\r\n");
      out.write("\t\"机场\",\"铁路\",\"道路\",\"河流水域\",\"公园绿地\",\r\n");
      out.write("\t\"防护绿地\"\r\n");
      out.write("];\r\n");
      out.write("var g_unitCategory=[\r\n");
      out.write("\t\"A3\",\"A3\",\"A3\",\"A3\",\"A3\",\r\n");
      out.write("\t\"A3\",\"A3\",\"A3\",\"A3\",\"A5\",\r\n");
      out.write("\t\"A5\",\"A5\",\"A6\",\"A6\",\"A6\",\r\n");
      out.write("\t\"A1\",\"A1\",\"A1\",\"A1\",\"A1\",\r\n");
      out.write("\t\"A6\",\"A6\",,\"A4\",\"A1\",\"A1\",\r\n");
      out.write("\t\"A2\",\"A6\",\"B3\",\"A2\",\"A2\",\r\n");
      out.write("\t\"B1\",\"B1\",\"B9\",\"B4\",\"B4\",\r\n");
      out.write("\t\"B4\",\"B4\",\"B4\",\"B4\",\"B4\",\r\n");
      out.write("\t\"B4\",\"A1\",\"A1\",\"A7\",\"G3\",\r\n");
      out.write("\t\"B9\",\"B9\",\"B9\",\"B9\",\"M\",\r\n");
      out.write("\t\"A\",\"A\",\"A\",\"B9\",\"B9\",\r\n");
      out.write("\t\"B9\",\"B9\",\"B9\",\"B9\",\"B9\",\r\n");
      out.write("\t\"B9\",\"B9\",\"B9\",\"B9\",\"B9\",\r\n");
      out.write("\t\"B9\",\"B9\",\"B9\",\"A1\",\"A1\",\r\n");
      out.write("\t\"W\",\"B9\",\"B9\",\"B9\",\"B9\",\r\n");
      out.write("\t\"B9\",\"B9\",\"B9\",\"B9\",\"B9\",\r\n");
      out.write("\t\"B9\",\"B9\",\"B9\",\"E1\",\"G1\",\r\n");
      out.write("\t\"G2\"\r\n");
      out.write("];\r\n");
      out.write("var typeColors=[\r\n");
      out.write("\t{type:'R',name:'居住用地',colorno: 50},\r\n");
      out.write("\t{type:'R1',name:'一类居住有地',colorno: 51},\r\n");
      out.write("\t{type:'R2',name:'二类居住有地',colorno: 50},\r\n");
      out.write("\t{type:'R3',name:'三类居住有地',colorno: 40},\r\n");
      out.write("\t{type:'A',name:'公共管理与公共服务用地',colorno: 231},\r\n");
      out.write("\t{type:'A1',name:'行政办公用地',colorno: 231},\r\n");
      out.write("\t{type:'A2',name:'文化设施用地',colorno: 241},\r\n");
      out.write("\t{type:'A3',name:'教育科研用地',colorno: 21},\r\n");
      out.write("\t{type:'A4',name:'体育用地',colorno: 62},\r\n");
      out.write("\t{type:'A5',name:'医疗卫生用地',colorno: 11},\r\n");
      out.write("\t{type:'A6',name:'社会福利设施用地',colorno: 243},\r\n");
      out.write("\t{type:'A7',name:'文物古迹用地',colorno: 244},\r\n");
      out.write("\t{type:'A8',name:'外事用地',colorno: 230},\r\n");
      out.write("\t{type:'A9',name:'宗教设施用地',colorno: 232},\r\n");
      out.write("\t{type:'B',name:'商业服务业设施用地',colorno: 240},\r\n");
      out.write("\t{type:'B1',name:'商业设施用地',colorno: 240},\r\n");
      out.write("\t{type:'B2',name:'商务设施用地',colorno: 240},\r\n");
      out.write("\t{type:'B3',name:'娱乐康体用地',colorno: 240},\r\n");
      out.write("\t{type:'B4',name:'公用设施营业网点用地',colorno: 240},\r\n");
      out.write("\t{type:'B9',name:'其它服务设施用地',colorno: 240},\r\n");
      out.write("\t{type:'M',name:'工业用地',colorno: 35},\r\n");
      out.write("\t{type:'M1',name:'一类工业用地',colorno: 35},\r\n");
      out.write("\t{type:'M2',name:'二类工业用地',colorno: 37},\r\n");
      out.write("\t{type:'M3',name:'三类工业用地',colorno: 39},\r\n");
      out.write("\t{type:'W',name:'物流仓储用地',colorno: 193},\r\n");
      out.write("\t{type:'W1',name:'一类物流仓储用地',colorno: 193},\r\n");
      out.write("\t{type:'W2',name:'二类物流仓储用地',colorno: 195},\r\n");
      out.write("\t{type:'W3',name:'三类物流仓储用地',colorno: 197},\r\n");
      out.write("\t{type:'S',name:'交通设施用地',colorno: 8},\r\n");
      out.write("\t{type:'S1',name:'城市道路用地',colorno: 8},\r\n");
      out.write("\t{type:'S2',name:'轨道交通线路用地',colorno: 8},\r\n");
      out.write("\t{type:'S3',name:'综合交通枢纽用地',colorno: 8},\r\n");
      out.write("\t{type:'S4',name:'交通场站用地',colorno: 8},\r\n");
      out.write("\t{type:'S9',name:'其它交通设施用地',colorno: 8},\r\n");
      out.write("\t{type:'U',name:'公用设施用地',colorno: 154},\r\n");
      out.write("\t{type:'U1',name:'供应设施用地',colorno: 154},\r\n");
      out.write("\t{type:'U2',name:'环境设施用地',colorno: 136},\r\n");
      out.write("\t{type:'U3',name:'安全设施用地',colorno: 144},\r\n");
      out.write("\t{type:'U9',name:'其它公用设施用地',colorno: 147},\r\n");
      out.write("\t{type:'G',name:'绿地',colorno:90},\r\n");
      out.write("\t{type:'G1',name:'公园绿地',colorno:90},\r\n");
      out.write("\t{type:'G2',name:'防护绿地',colorno:104},\r\n");
      out.write("\t{type:'G3',name:'广场用地',colorno:93},\r\n");
      out.write("\t{type:'H1',name:'城乡居民点建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H11',name:'城市建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H12',name:'镇建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H13',name:'乡建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H14',name:'村庄建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H15',name:'独立建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H2',name:'区域交通设施用地',colorno: 9},\r\n");
      out.write("\t{type:'H21',name:'铁路用地',colorno: 9},\r\n");
      out.write("\t{type:'H22',name:'公路用地',colorno: 9},\r\n");
      out.write("\t{type:'H23',name:'港口用地',colorno: 9},\r\n");
      out.write("\t{type:'H24',name:'机场用地',colorno: 9},\r\n");
      out.write("\t{type:'H25',name:'管道运输用地',colorno: 9},\r\n");
      out.write("\t{type:'H3',name:'区域公用设施用地',colorno: 156},\r\n");
      out.write("\t{type:'H4',name:'特殊用地',colorno:87},\r\n");
      out.write("\t{type:'H41',name:'军事用地',colorno:87},\r\n");
      out.write("\t{type:'H42',name:'安保用地',colorno:87},\r\n");
      out.write("\t{type:'H5',name:'采矿用地',colorno: 34},\r\n");
      out.write("\t{type:'E1',name:'水域',colorno:140},\r\n");
      out.write("\t{type:'E11',name:'自然水域',colorno:132},\r\n");
      out.write("\t{type:'E12',name:'水库',colorno:140},\r\n");
      out.write("\t{type:'E13',name:'坑塘沟渠',colorno:130},\r\n");
      out.write("\t{type:'E2',name:'农林用地',colorno: 82},\r\n");
      out.write("\t{type:'E3',name:'其它非建设用地',colorno:53},\r\n");
      out.write("\t{type:'E31',name:'空闲地',colorno:53},\r\n");
      out.write("\t{type:'E32',name:'其它非利用地',colorno:55}\r\n");
      out.write("];\r\n");
      out.write("\r\n");
      out.write("var colorIndexes=[\r\n");
      out.write("\t[0,0,0],[255,0,0],[255,255,0],[0,255,0],[0,255,255],[0,0,255],[255,0,255],[255,255,255],\r\n");
      out.write("\t[128,128,128],[192,192,192],[255,0,0],[255,127,127],[204,0,0],[204,102,102],[153,0,0],[153,76,76],\r\n");
      out.write("\t[127,0,0],[127,63,63],[76,0,0],[76,38,38],[255,63,0],[255,159,127],[204,51,0],[204,127,102],\r\n");
      out.write("\t[153,38,0],[153,95,76],[127,31,0],[127,79,63],[76,19,0],[76,47,38],[255,127,0],[255,191,127],\r\n");
      out.write("\t[204,102,0],[204,153,102],[153,76,0],[153,114,76],[127,63,0],[127,95,63],[76,38,0],[76,57,38],\r\n");
      out.write("\t[255,191,0],[255,223,127],[204,153,0],[204,178,102],[153,114,0],[153,133,76],[127,95,0],[127,111,63],\r\n");
      out.write("\t[76,57,0],[76,66,38],[255,255,0],[255,255,127],[204,204,0],[204,204,102],[153,153,0],[153,153,76],\r\n");
      out.write("\t[127,127,0],[127,127,63],[76,76,0],[76,76,38],[191,255,0],[223,255,127],[153,204,0],[178,204,102],\r\n");
      out.write("\t[114,153,0],[133,153,76],[95,127,0],[111,127,63],[57,76,0],[66,76,38],[127,255,0],[191,255,127],\r\n");
      out.write("\t[102,204,0],[153,204,102],[76,153,0],[114,153,76],[63,127,0],[95,127,63],[38,76,0],[57,76,38],\r\n");
      out.write("\t[63,255,0],[159,255,127],[51,204,0],[127,204,102],[38,153,0],[95,153,76],[31,127,0],[79,127,63],\r\n");
      out.write("\t[19,76,0],[47,76,38],[0,255,0],[127,255,127],[0,204,0],[102,204,102],[0,153,0],[76,153,76],\r\n");
      out.write("\t[0,127,0],[63,127,63],[0,76,0],[38,76,38],[0,255,63],[127,255,159],[0,204,51],[102,204,127],\r\n");
      out.write("\t[0,153,38],[76,153,95],[0,127,31],[63,127,79],[0,76,19],[38,76,47],[0,255,127],[127,255,191],\r\n");
      out.write("\t[0,204,102],[102,204,153],[0,153,76],[76,153,114],[0,127,63],[63,127,95],[0,76,38],[38,76,57],\r\n");
      out.write("\t[0,255,191],[127,255,223],[0,204,153],[102,204,178],[0,153,114],[76,153,133],[0,127,95],[63,127,111],\r\n");
      out.write("\t[0,76,57],[38,76,66],[0,255,255],[127,255,255],[0,204,204],[102,204,204],[0,153,153],[76,153,153],\r\n");
      out.write("\t[0,127,127],[63,127,127],[0,76,76],[38,76,76],[0,191,255],[127,223,255],[0,153,204],[102,178,204],\r\n");
      out.write("\t[0,114,153],[76,133,153],[0,95,127],[63,111,127],[0,57,76],[38,66,76],[0,127,255],[127,191,255],\r\n");
      out.write("\t[0,102,204],[102,153,204],[0,76,153],[76,114,153],[0,63,127],[63,95,127],[0,38,76],[38,57,76],\r\n");
      out.write("\t[0,63,255],[127,159,255],[0,51,204],[102,127,204],[0,38,153],[76,95,153],[0,31,127],[63,79,127],\r\n");
      out.write("\t[0,19,76],[38,47,76],[0,0,255],[127,127,255],[0,0,204],[102,102,204],[0,0,153],[76,76,153],\r\n");
      out.write("\t[0,0,127],[63,63,127],[0,0,76],[38,38,76],[63,0,255],[159,127,255],[51,0,204],[127,102,204],\r\n");
      out.write("\t[38,0,153],[95,76,153],[31,0,127],[79,63,127],[19,0,76],[47,38,76],[127,0,255],[191,127,255],\r\n");
      out.write("\t[102,0,204],[153,102,204],[76,0,153],[114,76,153],[63,0,127],[95,63,127],[38,0,76],[57,38,76],\r\n");
      out.write("\t[191,0,255],[223,127,255],[153,0,204],[178,102,204],[114,0,153],[133,76,153],[95,0,127],[111,63,127],\r\n");
      out.write("\t[57,0,76],[66,38,76],[255,0,255],[255,127,255],[204,0,204],[204,102,204],[153,0,153],[153,76,153],\r\n");
      out.write("\t[127,0,127],[127,63,127],[76,0,76],[76,38,76],[255,0,191],[255,127,223],[204,0,153],[204,102,178],\r\n");
      out.write("\t[153,0,114],[153,76,133],[127,0,95],[127,63,111],[76,0,57],[76,38,66],[255,0,127],[255,127,191],\r\n");
      out.write("\t[204,0,102],[204,102,153],[153,0,76],[153,76,114],[127,0,63],[127,63,95],[76,0,38],[76,38,57],\r\n");
      out.write("\t[255,0,63],[255,127,159],[204,0,51],[204,102,127],[153,0,38],[153,76,95],[127,0,31],[127,63,79],\r\n");
      out.write("\t[76,0,19],[76,38,47],[51,51,51],[91,91,91],[132,132,132],[173,173,173],[214,214,214],[255,255,255]\r\n");
      out.write("];\r\n");
      out.write("function intToHexString(v,len){\r\n");
      out.write("\tvar ret = v.toString(16);\r\n");
      out.write("\tif (ret.length < len){\r\n");
      out.write("\t\tvar a = len - ret.length;\r\n");
      out.write("\t\tfor(var i=0;i<a;i++){\r\n");
      out.write("\t\t\tret = '0' + ret;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn ret;\r\n");
      out.write("}\r\n");
      out.write("function getIndexColor(index){\r\n");
      out.write("    if (index < 0 || index >= colorIndexes.length){\r\n");
      out.write("    \treturn \"\";\r\n");
      out.write("    }\r\n");
      out.write("    var ret = '#';\r\n");
      out.write("    for(var i=0;i<3;i++){\r\n");
      out.write("    \tret += intToHexString(colorIndexes[index][i],2);\r\n");
      out.write("    }\r\n");
      out.write("    return ret;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var g_nodeNameMax=[20,24,20];\r\n");
      out.write("var g_nodeNameList={\r\n");
      out.write("\t\"xmkffw\": {\"name\": \"明确项目开发范围\", \"progress\": \"1\",\"index\":\"1\"},\r\n");
      out.write("\t\"xmcbys\": {\"name\": \"审核项目初步预算\", \"progress\": \"1\",\"index\":\"2\"},\r\n");
      out.write("\t\"shjcpw\": {\"name\": \"上会决策取得授权批文\", \"progress\": \"1\",\"index\":\"3\"},\r\n");
      out.write("\t\"kybzdwzb\": {\"name\": \"可研编制单位招标\", \"progress\": \"1\",\"index\":\"4\"},\r\n");
      out.write("\t\"tdkffa\": {\"name\": \"确定土地开发方案\", \"progress\": \"1\",\"index\":\"5\"},\r\n");
      out.write("\t\"kxxyjbg\": {\"name\": \"审核可行性研究报告\", \"progress\": \"1\",\"index\":\"6\"},\r\n");
      out.write("\t\"cwsh\": {\"name\": \"财务审核意见\", \"progress\": \"1\",\"index\":\"7\"},\r\n");
      out.write("\t\"rzsh\": {\"name\": \"融资部审核意见\", \"progress\": \"1\",\"index\":\"8\"},\r\n");
      out.write("\t\"xmsj\": {\"name\": \"项目审计意见\", \"progress\": \"1\",\"index\":\"9\"},\r\n");
      out.write("\t\"shjc\": {\"name\": \"上会决策\", \"progress\": \"1\",\"index\":\"10\"},\r\n");
      out.write("\t\"sfht\": {\"name\": \"三方合同拟定\", \"progress\": \"1\",\"index\":\"11\"},\r\n");
      out.write("\t\"htsh1\": {\"name\": \"合同审核\", \"progress\": \"1\",\"index\":\"12\"},\r\n");
      out.write("\t\"zfxs\": {\"name\": \"和属地政府协商\", \"progress\": \"1\",\"index\":\"13\"},\r\n");
      out.write("\t\"zjdw\": {\"name\": \"确认资金到位\", \"progress\": \"1\",\"index\":\"14\"},\r\n");
      out.write("\t\"gkzb\": {\"name\": \"公开招标\", \"progress\": \"1\",\"index\":\"15\"},\r\n");
      out.write("\t\"sfht\": {\"name\": \"四方合同拟定\", \"progress\": \"1\",\"index\":\"16\"},\r\n");
      out.write("\t\"htsh2\": {\"name\": \"合同审核\", \"progress\": \"1\",\"index\":\"17\"},\r\n");
      out.write("\t\"slggzh\": {\"name\": \"设立共管账户\", \"progress\": \"1\",\"index\":\"18\"},\r\n");
      out.write("\t\"ggxysh\": {\"name\": \"共管协议审核意见\", \"progress\": \"1\",\"index\":\"19\"},\r\n");
      out.write("\t\"qdggxy\": {\"name\": \"签订共管协议\", \"progress\": \"1\",\"index\":\"20\"},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\"tdsskf\": {\"name\": \"土地实施开发\", \"progress\": \"2\",\"index\":\"1\"},\r\n");
      out.write("\t\"jsbzdwzb\": {\"name\": \"精算编制单位招标\", \"progress\": \"2\",\"index\":\"2\"},\r\n");
      out.write("\t\"tjjsbg\": {\"name\": \"提交精算报告\", \"progress\": \"2\",\"index\":\"3\"},\r\n");
      out.write("\t\"shjsbg\": {\"name\": \"审核项目精算报告\", \"progress\": \"2\",\"index\":\"4\"},\r\n");
      out.write("\t\"xmss\": {\"name\": \"发起项目实施\", \"progress\": \"2\",\"index\":\"5\"},\r\n");
      out.write("\t\"qdht1\": {\"name\": \"签订合同\", \"progress\": \"2\",\"index\":\"6\"},\r\n");
      out.write("\t\"cbbhtba\": {\"name\": \"成本部合同备案\", \"progress\": \"2\",\"index\":\"7\"},\r\n");
      out.write("\t\"qdht2\": {\"name\": \"签订合同\", \"progress\": \"2\",\"index\":\"8\"},\r\n");
      out.write("\t\"cwbsh\": {\"name\": \"财务部审核\", \"progress\": \"2\",\"index\":\"9\"},\r\n");
      out.write("\t\"cbbshht\": {\"name\": \"成本部审核合同\", \"progress\": \"2\",\"index\":\"10\"},\r\n");
      out.write("\t\"sdwjgd\": {\"name\": \"三调文件归档\", \"progress\": \"2\",\"index\":\"11\"},\r\n");
      out.write("\t\"zfdqpw\": {\"name\": \"政府动迁批文\", \"progress\": \"2\",\"index\":\"12\"},\r\n");
      out.write("\t\"bcfa\": {\"name\": \"补偿方案\", \"progress\": \"2\",\"index\":\"13\"},\r\n");
      out.write("\t\"cbkzbba1\": {\"name\": \"成本控制部备案\", \"progress\": \"2\",\"index\":\"14\"},\r\n");
      out.write("\t\"shfxpg\": {\"name\": \"社会风险评估\", \"progress\": \"2\",\"index\":\"15\"},\r\n");
      out.write("\t\"xhjsbg\": {\"name\": \"细化精算报告\", \"progress\": \"2\",\"index\":\"16\"},\r\n");
      out.write("\t\"jsbgsh\": {\"name\": \"精算报告审核\", \"progress\": \"2\",\"index\":\"17\"},\r\n");
      out.write("\t\"cqgg\": {\"name\": \"政府征地拆迁公告\", \"progress\": \"2\",\"index\":\"18\"},\r\n");
      out.write("\t\"cqgz\": {\"name\": \"开展征地拆迁工作\", \"progress\": \"2\",\"index\":\"19\"},\r\n");
      out.write("\t\"cbkzbba2\": {\"name\": \"成本控制部备案\", \"progress\": \"2\",\"index\":\"20\"},\r\n");
      out.write("\t\"tdzs\": {\"name\": \"土地征收\", \"progress\": \"2\",\"index\":\"21\"},\r\n");
      out.write("\t\"wtjs\": {\"name\": \"委托建设\", \"progress\": \"2\",\"index\":\"22\"},\r\n");
      out.write("\t\"cbsh\": {\"name\": \"成本审核\", \"progress\": \"2\",\"index\":\"23\"},\r\n");
      out.write("\t\"ztyjh\": {\"name\": \"召开专题研究会\", \"progress\": \"2\",\"index\":\"24\"},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\"xmch\": {\"name\": \"项目策划\", \"progress\": \"3\",\"index\":\"1\"},\r\n");
      out.write("\t\"ghsh\": {\"name\": \"规划审核\", \"progress\": \"3\",\"index\":\"2\"},\r\n");
      out.write("\t\"fasj\": {\"name\": \"方案设计\", \"progress\": \"3\",\"index\":\"3\"},\r\n");
      out.write("\t\"wyhjy\": {\"name\": \"投资决策委员会决议\", \"progress\": \"3\",\"index\":\"4\"},\r\n");
      out.write("\t\"tzfa\": {\"name\": \"调整方案\", \"progress\": \"3\",\"index\":\"5\"},\r\n");
      out.write("\t\"fash1\": {\"name\": \"方案审核\", \"progress\": \"3\",\"index\":\"6\"},\r\n");
      out.write("\t\"sshjc\": {\"name\": \"上三会决策\", \"progress\": \"3\",\"index\":\"7\"},\r\n");
      out.write("\t\"tdlx\": {\"name\": \"项目立项\", \"progress\": \"3\",\"index\":\"8\"},\r\n");
      out.write("\t\"hqtdsyz\": {\"name\": \"获取土地使用证\", \"progress\": \"3\",\"index\":\"9\"},\r\n");
      out.write("\t\"bzkybg\": {\"name\": \"编制可研报告\", \"progress\": \"3\",\"index\":\"10\"},\r\n");
      out.write("\t\"shkybg\": {\"name\": \"审核可研报告\", \"progress\": \"3\",\"index\":\"11\"},\r\n");
      out.write("\t\"lxpf\": {\"name\": \"获取发改委立项批复\", \"progress\": \"3\",\"index\":\"12\"},\r\n");
      out.write("\t\"gszb\": {\"name\": \"专业公司招标\", \"progress\": \"3\",\"index\":\"13\"},\r\n");
      out.write("\t\"fatj\": {\"name\": \"方案提交\", \"progress\": \"3\",\"index\":\"14\"},\r\n");
      out.write("\t\"fash2\": {\"name\": \"方案审核\", \"progress\": \"3\",\"index\":\"15\"},\r\n");
      out.write("\t\"gcxk\": {\"name\": \"获取工程许可\", \"progress\": \"3\",\"index\":\"16\"},\r\n");
      out.write("\t\"gcsg\": {\"name\": \"工程施工\", \"progress\": \"3\",\"index\":\"17\"},\r\n");
      out.write("\t\"gcjs\": {\"name\": \"工程决算\", \"progress\": \"3\",\"index\":\"18\"},\r\n");
      out.write("\t\"gcsj\": {\"name\": \"工程审计报告备案\", \"progress\": \"3\",\"index\":\"19\"},\r\n");
      out.write("\t\"gcyj\": {\"name\": \"工程移交\", \"progress\": \"3\",\"index\":\"20\"}\r\n");
      out.write("};\r\n");
      out.write("function transNodeName(nodeName){\r\n");
      out.write("\tvar info = g_nodeNameList[nodeName];\r\n");
      out.write("\tif (null == info){\r\n");
      out.write("\t\treturn \"未知\";\r\n");
      out.write("\t}\r\n");
      out.write("\treturn info.name;\r\n");
      out.write("}\r\n");
      out.write("function getNodeNameList(progress){\r\n");
      out.write("\tvar ret = [];\r\n");
      out.write("\tfor(var key in g_nodeNameList){\r\n");
      out.write("\t\tvar value = g_nodeNameList[key];\r\n");
      out.write("\t\tif (progress == value.progress){\r\n");
      out.write("\t\t\tret.push(value.name);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn ret;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("jQuery(function($){ \r\n");
      out.write("     $.datepicker.regional['zh-CN'] = {   \r\n");
      out.write("        clearText: '清除',   \r\n");
      out.write("        clearStatus: '清除已选日期',   \r\n");
      out.write("        closeText: '关闭',   \r\n");
      out.write("        closeStatus: '不改变当前选择',   \r\n");
      out.write("        prevText: '<上月',   \r\n");
      out.write("        prevStatus: '显示上月',   \r\n");
      out.write("        prevBigText: '<<',   \r\n");
      out.write("        prevBigStatus: '显示上一年',   \r\n");
      out.write("        nextText: '下月>',   \r\n");
      out.write("        nextStatus: '显示下月',   \r\n");
      out.write("        nextBigText: '>>',   \r\n");
      out.write("        nextBigStatus: '显示下一年',   \r\n");
      out.write("        currentText: '今天',   \r\n");
      out.write("        currentStatus: '显示本月',   \r\n");
      out.write("        monthNames: ['一月','二月','三月','四月','五月','六月', '七月','八月','九月','十月','十一月','十二月'],   \r\n");
      out.write("        monthNamesShort: ['一月','二月','三月','四月','五月','六月', '七月','八月','九月','十月','十一月','十二月'],   \r\n");
      out.write("        monthStatus: '选择月份',   \r\n");
      out.write("        yearStatus: '选择年份',   \r\n");
      out.write("        weekHeader: '周',   \r\n");
      out.write("        weekStatus: '年内周次',   \r\n");
      out.write("        dayNames: ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],   \r\n");
      out.write("        dayNamesShort: ['周日','周一','周二','周三','周四','周五','周六'],   \r\n");
      out.write("        dayNamesMin: ['日','一','二','三','四','五','六'],   \r\n");
      out.write("        dayStatus: '设置 DD 为一周起始',   \r\n");
      out.write("        dateStatus: '选择 m月 d日, DD',   \r\n");
      out.write("        dateFormat: 'yy-mm-dd',   \r\n");
      out.write("        firstDay: 1,   \r\n");
      out.write("        initStatus: '请选择日期', \r\n");
      out.write("        showMonthAfterYear: true,\r\n");
      out.write("        yearSuffix: '年',\r\n");
      out.write("        isRTL: false\r\n");
      out.write("    };   \r\n");
      out.write("    $.datepicker.setDefaults($.datepicker.regional['zh-CN']);\r\n");
      out.write("    Globalize.culture(\"de-DE\");\r\n");
      out.write("    \r\n");
      out.write("    $.widget( \"ui.timespinner\", $.ui.spinner, {\r\n");
      out.write("        options: {\r\n");
      out.write("          // seconds\r\n");
      out.write("          step: 60 * 1000,\r\n");
      out.write("          // hours\r\n");
      out.write("          page: 60\r\n");
      out.write("        },\r\n");
      out.write("        _parse: function( value ) {\r\n");
      out.write("          if ( typeof value === \"string\" ) {\r\n");
      out.write("            // already a timestamp\r\n");
      out.write("            if ( Number( value ) == value ) {\r\n");
      out.write("              return Number( value );\r\n");
      out.write("            }\r\n");
      out.write("            return +Globalize.parseDate( value );\r\n");
      out.write("          }\r\n");
      out.write("          return value;\r\n");
      out.write("        },\r\n");
      out.write("     \r\n");
      out.write("        _format: function( value ) {\r\n");
      out.write("        \treturn Globalize.format( new Date(value), \"t\" );\r\n");
      out.write("        }\r\n");
      out.write("      });    \r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<title>位置和多边形区域设置</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#searchresult{\r\n");
      out.write("\t\tbackground: #FFF;\r\n");
      out.write("\t\twidth: 300px;\r\n");
      out.write("\t\tpadding: 7px 7px;\r\n");
      out.write("\t\tmargin-top: 10px;\r\n");
      out.write("\t\toverflow: auto;\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t#searchresult div.searchresult-item{\r\n");
      out.write("\t\tmargin-left: 5px;\r\n");
      out.write("\t\tmargin-top: 5px;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#searchresult div.searchresult-item.active{\r\n");
      out.write("\t\tbackground: #ddddFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t#searchresult div.searchresult-item div.item-icon{\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\twidth: 16px;\r\n");
      out.write("\t\theight: 32px;\r\n");
      out.write("\t\tbackground: url(images/circle-blue-16.png) center 3px no-repeat;\r\n");
      out.write("\t\tmargin-right: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#searchresult div.searchresult-item div.item-name{\r\n");
      out.write("\t\tfont-size: 1em;\r\n");
      out.write("\t\tline-height: 1.4em;\r\n");
      out.write("\t}\r\n");
      out.write("\t#searchresult div.searchresult-item div.item-addr{\r\n");
      out.write("\t\tfont-family: \"宋体\";\r\n");
      out.write("\t\tfont-size: 0.6em;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"container\" class=\"container\" tabindex=\"0\"></div>\r\n");
      out.write("    <div id=\"lefttop\">\r\n");
      out.write("    \t<div id=\"buttonsDiv\">\r\n");
      out.write("    \t\t<span\r\n");
      out.write("\t\t    \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \t\t>\r\n");
      out.write("\t\t    \t<input type=\"radio\" name=\"locatetype\" id=\"locatetype0\"\r\n");
      out.write("\t\t    \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    \t/><label class=\"forcheck\" for=\"locatetype0\">选择位置</label>\r\n");
      out.write("\t\t    \t<input type=\"radio\" name=\"locatetype\" id=\"locatetype1\"\r\n");
      out.write("\t\t    \t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    \t/><label class=\"forcheck\" for=\"locatetype1\">选择区域</label>\r\n");
      out.write("\t    \t</span>\r\n");
      out.write("\t    \t<span class=\"button\" id=\"startSel\" onclick=\"startSelect()\">选择</span>\r\n");
      out.write("\t    \t<span class=\"button\" id=\"editPolygon\" onclick=\"editPolygon()\" style=\"display:none;\">编辑区域</span>\r\n");
      out.write("\t    \t<span class=\"button\" onclick=\"save()\">保存</span>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div style=\"margin-top: 10px\">\r\n");
      out.write("    \t\t<input type=\"text\" id=\"searchText\" placeholder=\"地址、小区名称、建筑名称\" style=\"width:300px;\"/>\r\n");
      out.write("\t    \t<span class=\"button\" onclick=\"search()\">搜索</span>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div id=\"searchresult\">\r\n");
      out.write("    \t<!--\r\n");
      out.write("    \t\t<div class=\"searchresult-item\" index=\"0\">\r\n");
      out.write("    \t\t\t<div class=\"item-icon\"></div>\r\n");
      out.write("    \t\t\t<div class=\"item-name\">上海火车站</div>\r\n");
      out.write("    \t\t\t<div class=\"item-addr\">静安区秣陵路303号</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t-->\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("var placeSearch = null;\r\n");
      out.write("var g_startSel = false;\r\n");
      out.write("var g_markers=[];\r\n");
      out.write("var g_areaPolygon = null;\r\n");
      out.write("var g_otherMassifPolygon = [];\r\n");
      out.write("var g_curSeled = null;\r\n");
      out.write("var g_type = '';\r\n");
      out.write("var g_status = 0;\t\t\t//1 select; 2 edit polygon\r\n");
      out.write("var g_bSelPoint = false;\r\n");
      out.write("var g_polygonEditor = null;\r\n");
      out.write("var g_objType = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${objType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("var g_objID = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${objID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("var g_projID = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("$(function(){\r\n");
      out.write("\tamapinit({\r\n");
      out.write("\t\ttype:\"2D\",\r\n");
      out.write("\t\tshow:\"depart\",\r\n");
      out.write("\t\tdomIDName:\"container\",\r\n");
      out.write("\t\tclickfun:mapClick,\r\n");
      out.write("\t\tcomplete:mapLoaded\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#searchresult').on('click','div.searchresult-item',function(){\r\n");
      out.write("\t\t$('#searchresult div.searchresult-item').each(function(){\r\n");
      out.write("\t\t\t$(this).removeClass('active');\r\n");
      out.write("\t\t\tvar index = parseInt($(this).attr('index'));\r\n");
      out.write("\t\t\tif (isNaN(index) || g_markers.length <= index)\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\tg_markers[index].setTop(false);\r\n");
      out.write("\t\t\tg_markers[index].setIcon(\"images/circle-blue-16.png\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(this).addClass('active');\r\n");
      out.write("\t\tvar index = parseInt($(this).attr('index'));\r\n");
      out.write("\t\tif (isNaN(index) || g_markers.length <= index)\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\tg_markers[index].setTop(true);\r\n");
      out.write("\t\tg_markers[index].setIcon(\"images/circle-red-16.png\");\r\n");
      out.write("\t\tg_map.setCenter(g_markers[index].getPosition());\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function mapLoaded(){\r\n");
      out.write("\tAMap.plugin('AMap.Autocomplete',function(){\r\n");
      out.write("\t\tvar autoOptions = {\r\n");
      out.write("\t\t    city: \"昆明\",\r\n");
      out.write("\t\t    input:\"searchText\"\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tautocomplete= new AMap.Autocomplete(autoOptions);\r\n");
      out.write("\t});\r\n");
      out.write("\tAMap.service('AMap.PlaceSearch',function(){\r\n");
      out.write("\t    placeSearch= new AMap.PlaceSearch({\r\n");
      out.write("\t    \tcity:\"昆明\",\r\n");
      out.write("\t    \tcitylimit: true,\r\n");
      out.write("\t    \ttype:\"汽车服务|汽车销售|汽车维修|摩托车服务|餐饮服务|购物服务|生活服务|体育休闲服务|医疗保健服务|住宿服务|风景名胜|商务住宅|政府机构及社会团体|科教文化服务|交通设施服务|金融保险服务|公司企业|道路附属设施|地名地址信息|公共设施\",\r\n");
      out.write("\t    \tpageSize: 20,\r\n");
      out.write("\t    \tpageIndex: 1\r\n");
      out.write("\t    });\r\n");
      out.write("\t});\t\r\n");
      out.write("\tAMap.plugin(\"AMap.PolyEditor\");\r\n");
      out.write("\t\r\n");
      out.write("\tif (null != g_projID && g_projID.length > 0){\r\n");
      out.write("\t\t//如果是地块，先要读取所属的项目多边形\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajax.html?ajax=getLocation',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tdata: {'objtype':'area','objid':g_projID},\r\n");
      out.write("\t\t\ttimeout : 10000,\r\n");
      out.write("\t\t\tsuccess : function(msg, status) {\r\n");
      out.write("\t\t\t\tif (msg.status == 200) {\r\n");
      out.write("\t\t\t\t\tif (null != msg.data){\r\n");
      out.write("\t\t\t\t\t\tif (msg.data.iLocType==2){\r\n");
      out.write("\t\t\t\t\t\t\tvar pts = eval('('+msg.data.cPolygon+')');\r\n");
      out.write("\t\t\t\t\t\t\tg_areaPolygon = new AMap.Polygon({\r\n");
      out.write("\t\t\t\t\t\t        path: pts,\t\t\t//设置多边形边界路径\r\n");
      out.write("\t\t\t\t\t\t        strokeColor: '#F00', //线颜色\r\n");
      out.write("\t\t\t\t\t\t        strokeOpacity: 0.3, \t//线透明度\r\n");
      out.write("\t\t\t\t\t\t        strokeWeight: 2,    //线宽\r\n");
      out.write("\t\t\t\t\t\t        fillColor: '#F00', \t//填充色\r\n");
      out.write("\t\t\t\t\t\t        fillOpacity: 0.1,\t//填充透明度\r\n");
      out.write("\t\t\t\t\t\t        bubble: true\r\n");
      out.write("\t\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t\t\tg_areaPolygon.setMap(g_map);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tg_map.setFitView();\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t//读取此项目中已有的地块，除了编辑的地块之外\r\n");
      out.write("\t\t\t\t\t\t\treadOtherMassif();\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\treadAlreadyLocation();\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tnoArea();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tnoArea();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tshowError(msg.msg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(){\r\n");
      out.write("\t\t\t\tshowError('网络访问失败！');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\treadAlreadyLocation();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function noArea(){\r\n");
      out.write("\tshowError(\"所属项目还没有设置区域，请先设置项目区域\");\r\n");
      out.write("\t$('#buttonsDiv').hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function readOtherMassif(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajax.html?ajax=getMassif',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tdata: {'projid': g_projID},\r\n");
      out.write("\t\ttimeout : 10000,\r\n");
      out.write("\t\tsuccess : function(msg, status) {\r\n");
      out.write("\t\t\tif (msg.status == 200) {\r\n");
      out.write("\t\t\t\tif (null != msg.rows){\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<msg.rows.length;i++){\r\n");
      out.write("\t\t\t\t\t\tvar data = msg.rows[i];\r\n");
      out.write("\t\t\t\t\t\tif (data.cObjID != g_objID)\r\n");
      out.write("\t\t\t\t\t\t\tshowMassifPolygon(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tshowError(msg.msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(){\r\n");
      out.write("\t\t\tshowError('网络访问失败！');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\t\r\n");
      out.write("}\r\n");
      out.write("function showMassifPolygon(data){\r\n");
      out.write("    var strokeOpacity = 0.8; \t//线透明度\r\n");
      out.write("    var strokeWeight = 2;    \t//线宽\r\n");
      out.write("    var fillOpacity = 0.35;\t\t//填充透明度\r\n");
      out.write("\tvar pts = eval('('+data.cPolygon+')');\r\n");
      out.write("\tvar center = getCenter(pts);\r\n");
      out.write("    data[\"center\"]=center;\r\n");
      out.write("    \r\n");
      out.write("    var color = '#000000';\r\n");
      out.write("    var type = data.cCategory;\r\n");
      out.write("    var colorIndex = 0;\r\n");
      out.write("\tfor(var t=0;t<typeColors.length;t++){\r\n");
      out.write("\t\tif (type == typeColors[t].type){\r\n");
      out.write("\t\t\tcolorIndex = typeColors[t].colorno;\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif (colorIndex>0 && colorIndex < colorIndexes.length){\r\n");
      out.write("\t\tcolor = getIndexColor(colorIndex);\r\n");
      out.write("\t}\r\n");
      out.write("    var  polygon = new AMap.Polygon({\r\n");
      out.write("        path: pts,\t\t\t//设置多边形边界路径\r\n");
      out.write("        strokeColor: color, //线颜色\r\n");
      out.write("        strokeOpacity: strokeOpacity, \t//线透明度\r\n");
      out.write("        strokeWeight: strokeWeight,    \t//线宽\r\n");
      out.write("        fillColor: color, \t//填充色\r\n");
      out.write("        fillOpacity: fillOpacity,\t\t//填充透明度\r\n");
      out.write("        bubble: true,\r\n");
      out.write("        extData: data\r\n");
      out.write("    });\r\n");
      out.write("    polygon.setMap(g_map);\r\n");
      out.write("\tg_otherMassifPolygon.push(polygon);\r\n");
      out.write("\r\n");
      out.write("    polygon.on('click',function(){\r\n");
      out.write("    \tvar info = this.getExtData();\r\n");
      out.write("\t\tvar html=[];\r\n");
      out.write("\t\thtml.push('<div class=\"infowindow\">'); \t\t\r\n");
      out.write("\t\thtml.push('<div class=\"infotitle\">'+info.cMassifName+'</div>');\r\n");
      out.write("\t\thtml.push('<div class=\"infoline\">地块用途：');\r\n");
      out.write("\t\thtml.push(info.cUsage);\r\n");
      out.write("\t\thtml.push('</div>');\r\n");
      out.write("\t\thtml.push('<div class=\"infoline\">地块面积：');\r\n");
      out.write("\t\thtml.push(info.fAcreage+' 亩');\r\n");
      out.write("\t\thtml.push('</div>');\r\n");
      out.write("\t\thtml.push('<div class=\"infoline\">开始日期：');\r\n");
      out.write("\t\thtml.push(info.dtStart);\r\n");
      out.write("\t\thtml.push('</div>');\r\n");
      out.write("\t\thtml.push('</div>');\r\n");
      out.write("    \tshowInfoWindow(info.center,html.join(''));\r\n");
      out.write("    });\r\n");
      out.write("    polygon.on('rightclick',function(){});\r\n");
      out.write("    \r\n");
      out.write("\tvar showName = new AMap.Text({\r\n");
      out.write("        text: data.cMassifName,\r\n");
      out.write("        textAlign:'center', // 'left' 'right', 'center',\r\n");
      out.write("        verticalAlign:'middle', //middle 、bottom\r\n");
      out.write("        draggable:false,\r\n");
      out.write("        cursor:'pointer',\r\n");
      out.write("        style:{\r\n");
      out.write("            'background':'transparent',\r\n");
      out.write("\t           'border':'none',\r\n");
      out.write("\t           'color':'white',\r\n");
      out.write("            'padding':'0px 0px',\r\n");
      out.write("            'font-size': '8px'\r\n");
      out.write("        },\r\n");
      out.write("        bubble: false,\r\n");
      out.write("        position: center\r\n");
      out.write("    });\r\n");
      out.write("    showName.setMap(g_map);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function readAlreadyLocation(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajax.html?ajax=getLocation',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tdata: {'objtype':g_objType,'objid':g_objID},\r\n");
      out.write("\t\ttimeout : 10000,\r\n");
      out.write("\t\tsuccess : function(msg, status) {\r\n");
      out.write("\t\t\tif (msg.status == 200) {\r\n");
      out.write("\t\t\t\tif (null != msg.data){\r\n");
      out.write("\t\t\t\t\tif (msg.data.iLocType==2){\r\n");
      out.write("\t\t\t\t\t\tvar pts = eval('('+msg.data.cPolygon+')');\r\n");
      out.write("\t\t\t\t\t\tvar polygon = new AMap.Polygon({\r\n");
      out.write("\t\t\t\t\t        path: pts,\t\t\t//设置多边形边界路径\r\n");
      out.write("\t\t\t\t\t        strokeColor: '#00F', //线颜色\r\n");
      out.write("\t\t\t\t\t        strokeOpacity: 1, \t//线透明度\r\n");
      out.write("\t\t\t\t\t        strokeWeight: 2,    \t//线宽\r\n");
      out.write("\t\t\t\t\t        fillColor: '#00F', \t//填充色\r\n");
      out.write("\t\t\t\t\t        fillOpacity: 0.3,\t\t//填充透明度\r\n");
      out.write("\t\t\t\t\t        bubble: false\r\n");
      out.write("\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t\tpolygon.setMap(g_map);\r\n");
      out.write("\t\t\t\t\t\tdrawOver(polygon);\r\n");
      out.write("\t\t\t\t\t\t$('#locatetype0').removeAttr('checked');\r\n");
      out.write("\t\t\t\t\t\t$('#locatetype1').attr('checked','checked');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tg_map.setFitView();\r\n");
      out.write("\t\t\t\t\t}else if (msg.data.iLocType==1){\r\n");
      out.write("\t\t\t\t\t\tshowPtMarker([msg.data.fLng,msg.data.fLat],msg.data.cAddr);\r\n");
      out.write("\t\t\t\t\t\t$('#locatetype1').removeAttr('checked');\r\n");
      out.write("\t\t\t\t\t\t$('#locatetype0').attr('checked','checked');\r\n");
      out.write("\t\t\t\t\t\tg_map.setCenter(new AMap.LngLat(msg.data.fLng,msg.data.fLat));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tshowError(msg.msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(){\r\n");
      out.write("\t\t\tshowError('网络访问失败！');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkPtInAreaPoligon(pt){\r\n");
      out.write("\tif (null == g_areaPolygon || g_objType!='massif')\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\treturn g_areaPolygon.contains(pt);\r\n");
      out.write("}\r\n");
      out.write("function checkPoligonInAreaPoligon(poligon){\r\n");
      out.write("\tif (null == g_areaPolygon || g_objType!='massif'){\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar ret = AMap.GeometryUtil.isRingInRing(poligon.getPath(),g_areaPolygon.getPath());\r\n");
      out.write("\treturn ret;\r\n");
      out.write("}\r\n");
      out.write("function checkPoligonCrossOtherPoligon(poligon){\r\n");
      out.write("\tif (null == g_areaPolygon || g_objType!='massif'){\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar ret = true;\r\n");
      out.write("\tvar pts = poligon.getPath();\r\n");
      out.write("\tfor(var i=0;i<g_otherMassifPolygon.length;i++){\r\n");
      out.write("\t\tvar isCross = AMap.GeometryUtil.doesRingRingIntersect(pts,g_otherMassifPolygon[i].getPath());\r\n");
      out.write("\t\tif (isCross){\r\n");
      out.write("\t\t\tret = false;\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn ret;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function mapClick(pt,formatAddr){\r\n");
      out.write("\tif (true != g_bSelPoint)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tif (null != g_curSeled){\r\n");
      out.write("\t\tg_map.remove(g_curSeled);\r\n");
      out.write("\t\tg_curSeled = null;\r\n");
      out.write("\t}\r\n");
      out.write("\tshowPtMarker(pt,formatAddr);\r\n");
      out.write("}\r\n");
      out.write("function showPtMarker(pt,formatAddr){\r\n");
      out.write("\tif (!checkPtInAreaPoligon(pt)){\r\n");
      out.write("\t\tshowError(\"选择的位置未在项目区域内，请重新选择\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tg_curSeled = new AMap.Marker({\r\n");
      out.write("\t\tposition: pt\r\n");
      out.write("\t});\r\n");
      out.write("\tg_curSeled.setTop(true);\r\n");
      out.write("\tg_curSeled.setMap(g_map);\r\n");
      out.write("\tg_curSeled.setTitle(formatAddr);\r\n");
      out.write("\tg_type = \"point\";\r\n");
      out.write("\t\r\n");
      out.write("\tg_curSeled.on('click',function(){\r\n");
      out.write("\t\tvar title = this.getTitle();\r\n");
      out.write("\t\tvar curPt = this.getPosition();\r\n");
      out.write("\t\tvar html=[];\r\n");
      out.write("\t\thtml.push('<div class=\"infowindow\">');\r\n");
      out.write("\t\thtml.push('<div class=\"infotitle\">当前位置</div>');\r\n");
      out.write("\t\tif (null != title && '' != title) {\r\n");
      out.write("\t\t\thtml.push('<div class=\"infoline\">地址：'+ title + '</div>');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\thtml.push('<div class=\"infoline\">坐标：');\r\n");
      out.write("\t\thtml.push(curPt.getLng()+' , '+curPt.getLat());\r\n");
      out.write("\t\thtml.push('</div>');\r\n");
      out.write("\t\thtml.push('</div>');\r\n");
      out.write("\t\tshowInfoWindow(curPt,html.join(''),new AMap.Pixel(0,-30));\r\n");
      out.write("\t});\t\r\n");
      out.write("\tvar html=[];\r\n");
      out.write("\thtml.push('<div class=\"infowindow\">');\r\n");
      out.write("\thtml.push('<div class=\"infotitle\">当前位置</div>');\r\n");
      out.write("\tif (null != formatAddr && '' != formatAddr) {\r\n");
      out.write("\t\thtml.push('<div class=\"infoline\">地址：'+ formatAddr + '</div>');\r\n");
      out.write("\t}\r\n");
      out.write("\thtml.push('<div class=\"infoline\">坐标：');\r\n");
      out.write("\thtml.push(pt[0]+' , '+pt[1]);\r\n");
      out.write("\thtml.push('</div>');\r\n");
      out.write("\thtml.push('</div>');\r\n");
      out.write("\tshowInfoWindow(pt,html.join(''),new AMap.Pixel(0,-30));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function startSelect(){\r\n");
      out.write("\tif (g_status == 2)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tvar $sel = $('#startSel'); \r\n");
      out.write("\tif ($sel.html()=='选择'){\r\n");
      out.write("\t\tif ($('#locatetype0').is(':checked')){\r\n");
      out.write("\t\t\tg_bSelPoint = true;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tstartDraw(\"polygon\",drawOver);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$sel.html('结束');\r\n");
      out.write("\t\tif (null != g_curSeled){\r\n");
      out.write("\t\t\tg_map.remove(g_curSeled);\r\n");
      out.write("\t\t\tg_curSeled = null;\r\n");
      out.write("\t\t\t$('#editPolygon').hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tcloseInfoWindow();\r\n");
      out.write("\t\tg_status = 1;\t\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$sel.html('选择');\r\n");
      out.write("\t\tg_bSelPoint = false;\r\n");
      out.write("\t\tg_status = 0;\r\n");
      out.write("\t\tendDraw();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function editPolygon(){\r\n");
      out.write("\tif (g_status == 1)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tif (null != g_polygonEditor){\r\n");
      out.write("\t\tg_polygonEditor.close();\r\n");
      out.write("\t\tg_polygonEditor = null;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($('#editPolygon').html()=='结束编辑'){\r\n");
      out.write("\t\t$('#editPolygon').html('编辑区域');\r\n");
      out.write("\t\tg_status=0;\r\n");
      out.write("\t\tif (!checkPoligonInAreaPoligon(g_curSeled)){\r\n");
      out.write("\t\t\tshowError(\"绘制的区域超出来项目的红线范围，请重新选择或编辑\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!checkPoligonCrossOtherPoligon(g_curSeled)){\r\n");
      out.write("\t\t\tshowError(\"绘制的区域与其它地块有交叉，请重新选择或编辑\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (null == g_curSeled || g_type != \"polygon\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t$('#editPolygon').html('结束编辑');\r\n");
      out.write("\tg_polygonEditor= new AMap.PolyEditor(g_map, g_curSeled);\r\n");
      out.write("\tg_polygonEditor.open();\r\n");
      out.write("\tg_status = 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function drawOver(polygon){\r\n");
      out.write("\tg_curSeled = polygon;\r\n");
      out.write("\tg_type = \"polygon\";\r\n");
      out.write("\t$('#startSel').html('选择');\r\n");
      out.write("\tg_bSelPoint = false;\r\n");
      out.write("\tg_status = 0;\r\n");
      out.write("\t$('#editPolygon').show();\r\n");
      out.write("\t\r\n");
      out.write("\tif (!checkPoligonInAreaPoligon(polygon)){\r\n");
      out.write("\t\tshowError(\"绘制的区域超出来项目的红线范围，请重新选择或编辑\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (!checkPoligonCrossOtherPoligon(g_curSeled)){\r\n");
      out.write("\t\tshowError(\"绘制的区域与其它地块有交叉，请重新选择或编辑\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function search(){\r\n");
      out.write("\t$('#searchresult').html('');\r\n");
      out.write("\t$('#searchresult').hide();\r\n");
      out.write("\tvar text = $('#searchText').val().trim();\r\n");
      out.write("\tif (text == '')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tif (null == placeSearch)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tg_map.remove(g_markers);\r\n");
      out.write("\tg_markers=[];\r\n");
      out.write("\tplaceSearch.search(text,function(status,result){\r\n");
      out.write("\t\tvar resultDom = $('#searchresult');\r\n");
      out.write("\t\tif (status != 'complete' || result.info != 'OK'){\r\n");
      out.write("\t\t\tresultDom.html('没有搜索到匹配结果');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor(var i=0;i<result.poiList.pois.length;i++){\r\n");
      out.write("\t\t\t\tvar poi = result.poiList.pois[i];\r\n");
      out.write("\t\t\t\tvar item=[];\r\n");
      out.write("\t    \t\titem.push('<div class=\"searchresult-item\" index=\"'+i+'\">');\r\n");
      out.write("\t    \t\titem.push('<div class=\"item-icon\"></div>');\r\n");
      out.write("\t    \t\titem.push('<div class=\"item-name\">'+poi.name+'</div>');\r\n");
      out.write("\t    \t\titem.push('<div class=\"item-addr\">'+poi.address+'</div>');\r\n");
      out.write("\t    \t\titem.push('</div>');\r\n");
      out.write("\t    \t\tresultDom.append(item.join(''));\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\tvar marker = new AMap.Marker({\r\n");
      out.write("\t    \t\t\ticon: \"images/circle-blue-16.png\",\r\n");
      out.write("\t    \t\t\tbubble: true,\r\n");
      out.write("\t    \t\t\tposition: poi.location\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t    \t\tmarker.setMap(g_map);\r\n");
      out.write("\t    \t\tmarker.setTitle(poi.name);\r\n");
      out.write("\t    \t\tg_markers.push(marker);\r\n");
      out.write("\t    \t\tmarker.on('mouseover',function(){\r\n");
      out.write("\t    \t\t\tvar title = this.getTitle();\r\n");
      out.write("\t    \t\t\tthis.setLabel({//label默认蓝框白底左上角显示，样式className为：amap-marker-label\r\n");
      out.write("\t    \t\t        offset: new AMap.Pixel(20, 20),//label相对于maker的位置\r\n");
      out.write("\t    \t\t        content: title\r\n");
      out.write("\t    \t\t    });\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t    \t\tmarker.on('mouseout',function(){\r\n");
      out.write("\t    \t\t\tthis.setLabel({});\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tg_map.setFitView();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tresultDom.show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar top = resultDom.offset().top;\r\n");
      out.write("\t\tvar fullHeight = $(window).height();\r\n");
      out.write("\t\tresultDom.height(fullHeight - top - 30);\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function save(){\r\n");
      out.write("\tif (null == g_curSeled){\r\n");
      out.write("\t\tshowError(\"当前没有选择\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar params={};\r\n");
      out.write("\tparams.objtype = g_objType;\r\n");
      out.write("\tparams.objid= g_objID;\r\n");
      out.write("\tparams.projid= g_projID;\r\n");
      out.write("\tif (g_type == \"polygon\"){\r\n");
      out.write("\t\tif (!checkPoligonInAreaPoligon(g_curSeled)){\r\n");
      out.write("\t\t\tshowError(\"绘制的区域超出了项目的红线范围，请重新选择或编辑\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!checkPoligonCrossOtherPoligon(g_curSeled)){\r\n");
      out.write("\t\t\tshowError(\"绘制的区域与其它地块有交叉，请重新选择或编辑\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tparams.loctype = 2;\r\n");
      out.write("\t\tvar pts = g_curSeled.getPath();\r\n");
      out.write("\t\tvar out=[];\r\n");
      out.write("\t\tout.push('[');\r\n");
      out.write("\t\tfor(var i=0;i<pts.length;i++){\r\n");
      out.write("\t\t\tif (i>0) out.push(',');\r\n");
      out.write("\t\t\tout.push('[');\r\n");
      out.write("\t\t\tout.push(pts[i].getLng());\r\n");
      out.write("\t\t\tout.push(',');\r\n");
      out.write("\t\t\tout.push(pts[i].getLat());\r\n");
      out.write("\t\t\tout.push(']');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tout.push(']');\r\n");
      out.write("\t\tparams.polygon = out.join('');\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tif (!checkPtInAreaPoligon(g_curSeled.getPosition())){\r\n");
      out.write("\t\t\tshowError(\"选择的位置不在项目的红线范围内，请重新选择\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tparams.loctype = 1;\r\n");
      out.write("\t\tparams.lng = g_curSeled.getPosition().getLng();\r\n");
      out.write("\t\tparams.lat = g_curSeled.getPosition().getLat();\r\n");
      out.write("\t\tparams.addr = g_curSeled.getTitle();\r\n");
      out.write("\t}\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajax.html?ajax=editLocation',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tdata: params,\r\n");
      out.write("\t\ttimeout : 10000,\r\n");
      out.write("\t\tsuccess : function(msg, status) {\r\n");
      out.write("\t\t\tif (msg.status == 200) {\r\n");
      out.write("\t\t\t\tshowMessage(\"保存成功！\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tshowError(msg.msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(){\r\n");
      out.write("\t\t\tshowError('网络访问失败！');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /backglobal.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("urlhead");
      // /backglobal.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /setptpoligon.jsp(51,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selType!=0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t    \tstyle=\"display:none;\" \r\n");
          out.write("\t\t    \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /setptpoligon.jsp(56,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selType==0 || selType==1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t    \tchecked=\"checked\"\r\n");
          out.write("\t\t    \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /setptpoligon.jsp(61,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selType==2}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t    \tchecked=\"checked\"\r\n");
          out.write("\t\t    \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
