/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2017-03-31 08:34:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sysman_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/pagetop.jsp", Long.valueOf(1489991632954L));
    _jspx_dependants.put("/WEB-INF/tlds/fn.tld", Long.valueOf(1384075602268L));
    _jspx_dependants.put("/backglobal.jsp", Long.valueOf(1489575771187L));
    _jspx_dependants.put("/global.jsp", Long.valueOf(1490949253134L));
    _jspx_dependants.put("/bottom.jsp", Long.valueOf(1489920971028L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1384075544509L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html class=\"main\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery-ui.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/global.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/combox.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery-ui-timepicker-addon.css\" />\r\n");
      out.write("<script type=text/javascript src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery.form.min.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/common.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/globalize.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/globalize.culture.de-DE.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/combox.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery-ui-timepicker-addon.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery.ui.datepicker-zh-CN.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery-ui-timepicker-zh-CN.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=text/javascript src=\"modules/modules.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/Tdrag.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/dialog/dialog.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/messagebox.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/labelinput/labelinput.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/mainframe/mainframe.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/frametop/frametop.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/chgpwd/chgpwd.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/leftmenu/leftmenu.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/button/button.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/condgroup/condgroup.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/datagrid/datagrid.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"modules/uploadfile/uploadfile.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/SimpleGrid.css\" />\r\n");
      out.write("<script type=text/javascript src=\"js/SimpleGrid.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("jQuery(function($){ \r\n");
      out.write("     $.datepicker.regional['zh-CN'] = {   \r\n");
      out.write("        clearText: '清除',   \r\n");
      out.write("        clearStatus: '清除已选日期',   \r\n");
      out.write("        closeText: '关闭',   \r\n");
      out.write("        closeStatus: '不改变当前选择',   \r\n");
      out.write("        prevText: '<上月',   \r\n");
      out.write("        prevStatus: '显示上月',   \r\n");
      out.write("        prevBigText: '<<',   \r\n");
      out.write("        prevBigStatus: '显示上一年',   \r\n");
      out.write("        nextText: '下月>',   \r\n");
      out.write("        nextStatus: '显示下月',   \r\n");
      out.write("        nextBigText: '>>',   \r\n");
      out.write("        nextBigStatus: '显示下一年',   \r\n");
      out.write("        currentText: '今天',   \r\n");
      out.write("        currentStatus: '显示本月',   \r\n");
      out.write("        monthNames: ['一月','二月','三月','四月','五月','六月', '七月','八月','九月','十月','十一月','十二月'],   \r\n");
      out.write("        monthNamesShort: ['一月','二月','三月','四月','五月','六月', '七月','八月','九月','十月','十一月','十二月'],   \r\n");
      out.write("        monthStatus: '选择月份',   \r\n");
      out.write("        yearStatus: '选择年份',   \r\n");
      out.write("        weekHeader: '周',   \r\n");
      out.write("        weekStatus: '年内周次',   \r\n");
      out.write("        dayNames: ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],   \r\n");
      out.write("        dayNamesShort: ['周日','周一','周二','周三','周四','周五','周六'],   \r\n");
      out.write("        dayNamesMin: ['日','一','二','三','四','五','六'],   \r\n");
      out.write("        dayStatus: '设置 DD 为一周起始',   \r\n");
      out.write("        dateStatus: '选择 m月 d日, DD',   \r\n");
      out.write("        dateFormat: 'yy-mm-dd',   \r\n");
      out.write("        firstDay: 1,   \r\n");
      out.write("        initStatus: '请选择日期', \r\n");
      out.write("        showMonthAfterYear: true,\r\n");
      out.write("        yearSuffix: '年',\r\n");
      out.write("        isRTL: false\r\n");
      out.write("    };   \r\n");
      out.write("    $.datepicker.setDefaults($.datepicker.regional['zh-CN']);\r\n");
      out.write("    Globalize.culture(\"de-DE\");\r\n");
      out.write("    \r\n");
      out.write("    $.widget( \"ui.timespinner\", $.ui.spinner, {\r\n");
      out.write("        options: {\r\n");
      out.write("          // seconds\r\n");
      out.write("          step: 60 * 1000,\r\n");
      out.write("          // hours\r\n");
      out.write("          page: 60\r\n");
      out.write("        },\r\n");
      out.write("        _parse: function( value ) {\r\n");
      out.write("          if ( typeof value === \"string\" ) {\r\n");
      out.write("            // already a timestamp\r\n");
      out.write("            if ( Number( value ) == value ) {\r\n");
      out.write("              return Number( value );\r\n");
      out.write("            }\r\n");
      out.write("            return +Globalize.parseDate( value );\r\n");
      out.write("          }\r\n");
      out.write("          return value;\r\n");
      out.write("        },\r\n");
      out.write("     \r\n");
      out.write("        _format: function( value ) {\r\n");
      out.write("        \treturn Globalize.format( new Date(value), \"t\" );\r\n");
      out.write("        }\r\n");
      out.write("      });    \r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var pageTop = null;\r\n");
      out.write("function initTop(mainframe){\r\n");
      out.write("\tpageTop = new FrametopModule();\r\n");
      out.write("\tpageTop.config({\r\n");
      out.write("\t\tsysname: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\tusername: \"\",\r\n");
      out.write("\t\tchgpwdCallback: function(data){\r\n");
      out.write("\t\t\treturn commitChgPwd(data);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texitCallback: function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxpage.html?ajax=logout',\r\n");
      out.write("\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\tdata :{}\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login.html\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tpageTop.initDom();\r\n");
      out.write("\tif (mainframe instanceof MainframeModule)\r\n");
      out.write("\t\tmainframe.set(\"appendTop\",pageTop);\r\n");
      out.write("\telse\r\n");
      out.write("\t\tpageTop.mydom.appendTo(mainframe);\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxpage.html?ajax=getCurUser',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tdata :{},\r\n");
      out.write("\t\ttimeout : 10000,\r\n");
      out.write("\t\tsuccess : function(msg, status) {\r\n");
      out.write("\t\t\tif (msg.status == 200) {\r\n");
      out.write("\t\t\t\tif (null != msg.realName && msg.realName != '')\r\n");
      out.write("\t\t\t\t\tpageTop.set(\"username\",msg.realName);\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tpageTop.set(\"username\",msg.userName);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/index.html\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/index.html\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}); \t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function commitChgPwd(data){\r\n");
      out.write("\tvar bRet = false;\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxpage.html?ajax=changepwd',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tasync: false,\r\n");
      out.write("\t\tdata: data,\t\t//{curpwd:xxx,newpwd:xxx},   \r\n");
      out.write("\t\ttimeout : 10000,\r\n");
      out.write("\t\tsuccess : function(msg, status) {\r\n");
      out.write("\t\t\tif (msg.status == 200) {\r\n");
      out.write("\t\t\t\tshowMessage('修改密码成功！');\r\n");
      out.write("\t\t\t\tbRet = true;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tshowError(msg.msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\treturn bRet;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function initBottom(mainframe){\r\n");
      out.write("\tmainframe.set(\"appendBottom\",$(\"<div style='margin:15px;'>Copyright &copy; ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${copyright}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t+ \"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\"\r\n");
      out.write("\t\t\t+ \"</div>\")\r\n");
      out.write("\t);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var mainframe = null;\r\n");
      out.write("$(function(){\r\n");
      out.write("\tmainframe = new MainframeModule();\r\n");
      out.write("\tmainframe.config({\r\n");
      out.write("\t\t//allowHideMenu: true,\r\n");
      out.write("\t\tframeBorderWidth: 3,\r\n");
      out.write("\t\ttopBackground: \"url(images/top.png)\",\r\n");
      out.write("\t\tmenuBackground: \"#EEE\"\r\n");
      out.write("\t});\r\n");
      out.write("\tmainframe.initDom();\r\n");
      out.write("\tinitTop(mainframe);\r\n");
      out.write("\t\r\n");
      out.write("\tvar menu = new LeftmenuModule();\r\n");
      out.write("\tmenu.config({\r\n");
      out.write("\t\tmenus:[\r\n");
      out.write("\t\t       {group:{name:\"massgroup\",display:\"地块管理\"},active: true,\r\n");
      out.write("\t\t\t\titems:[{name:\"payobjman\",display:\"支付对象管理\"},\r\n");
      out.write("\t\t\t\t       {name:\"massman\",display:\"地块管理\"},\r\n");
      out.write("\t\t\t\t       {name:\"closedman\",display:\"结案处理\"}\r\n");
      out.write("\t\t\t\t      ]\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       {group:{name:\"inoutgroup\",display:\"出入账管理\"},\r\n");
      out.write("\t\t    \titems:[{name:\"incomeman\",display:\"入账管理\"},\r\n");
      out.write("\t\t    \t       {name:\"masspayman\",display:\"地块出账\"},\r\n");
      out.write("\t\t    \t       {name:\"nomasspayman\",display:\"无地块出账\"}\r\n");
      out.write("\t\t    \t      ]\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       {group:{name:\"statgroup\",display:\"查询统计\"},\r\n");
      out.write("\t\t    \titems:[{name:\"masssearch\",display:\"地块查询\"},\r\n");
      out.write("\t\t    \t       {name:\"inoutstat\",display:\"出入账统计\"},\r\n");
      out.write("\t\t    \t       {name:\"closedsearch\",display:\"结案查询\"}\r\n");
      out.write("\t\t    \t       ]\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       {group:{name:\"sysgroup\",display:\"系统管理\"},\r\n");
      out.write("\t\t    \titems:[{name:\"sysuserman\",display:\"用户管理\"}\r\n");
      out.write("\t\t    \t\t  ]\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t],\r\n");
      out.write("\t\titemAction: menuClick\r\n");
      out.write("\t});\r\n");
      out.write("\tmenu.initDom();\r\n");
      out.write("\tmainframe.set(\"appendMenu\",menu);\r\n");
      out.write("\tinitBottom(mainframe);\r\n");
      out.write("\tmainframe.render();\r\n");
      out.write("});\r\n");
      out.write("function menuClick(name,extinfo){\r\n");
      out.write("\tif (extinfo == \"newwindow\"){\r\n");
      out.write("\t\twindow.open(\"index.html?action=selmenu&name=\"+name);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tmainframe.set(\"contentUrl\",\"index.html?action=selmenu&name=\"+name);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /backglobal.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("urlhead");
    // /backglobal.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /backglobal.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("sysname");
    // /backglobal.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new String("土地信息管理系统"));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /backglobal.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("copyright");
    // /backglobal.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue(new String("闵行区财政局"));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }
}
