/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2018-07-11 02:33:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tlds/fn.tld", Long.valueOf(1384075604000L));
    _jspx_dependants.put("/backglobal.jsp", Long.valueOf(1527385603000L));
    _jspx_dependants.put("/global.jsp", Long.valueOf(1531273484000L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1384075546000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=text/javascript src=\"js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("<script type=text/javascript src=\"js/jquery.form.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var g_largeType=[\r\n");
      out.write("    \"教育\",\"医疗\",\"商业\",\"公共服务\",\"交通\",\"行政办公\",\"其他\"\r\n");
      out.write("];\r\n");
      out.write("var g_unitType=[\r\n");
      out.write("\t[\r\n");
      out.write("\t \"托儿所\",\"小学\",\"初中\",\"高中\",\"中专大专\",\"高等院校\",\"其他\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"综合医院\",\"专科医院\",\"卫生服务中心\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"体育活动中心\",\"社区文化站\",\"社区健身场\",\"综合超市\",\"大型购物中心\",\"社区肉菜市场\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"青少年活动中心\",\"敬老院\",\"老年人活动站\",\"社区文娱中心\",\"社区警务室\",\"社区服务站\",\"图书馆\",\"网络通信服务\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"地铁站\",\"公交站\",\"火车站\",\"飞机场\",\"长途客运站\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"党政机关\",\"公安局\",\"街道办事处\",\"街道派出所\",\"社区居委会\",\"社区服务中心\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"绿地\",\"危险品仓库\",\"垃圾焚烧厂\",\"垃圾填埋厂\",\"高压变电站\",\"加油加气站\"\r\n");
      out.write("\t]\r\n");
      out.write("];\r\n");
      out.write("var g_unitCategory=[\r\n");
      out.write("\t[\r\n");
      out.write("\t \"A3\",\"A3\",\"A3\",\"A3\",\"A3\",\"A3\",\"A3\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"A5\",\"A5\",\"A5\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"A4\",\"A2\",\"A6\",\"B1\",\"B1\",\"B9\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"A6\",\"A6\",\"A6\",\"A6\",\"A1\",\"A1\",\"A1\",\"B4\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"B9\",\"B9\",\"B9\",\"B9\",\"B9\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"A1\",\"A1\",\"A1\",\"A1\",\"A1\",\"A6\"\r\n");
      out.write("\t],[\r\n");
      out.write("\t \"G1\",\"M\",\"B9\",\"B9\",\"A\",\"W\"\r\n");
      out.write("\t]\r\n");
      out.write("];\r\n");
      out.write("var typeColors=[\r\n");
      out.write("\t{type:'R',name:'居住用地',colorno: 50},\r\n");
      out.write("\t{type:'R1',name:'一类居住有地',colorno: 51},\r\n");
      out.write("\t{type:'R2',name:'二类居住有地',colorno: 50},\r\n");
      out.write("\t{type:'R3',name:'三类居住有地',colorno: 40},\r\n");
      out.write("\t{type:'A',name:'公共管理与公共服务用地',colorno: 231},\r\n");
      out.write("\t{type:'A1',name:'行政办公用地',colorno: 231},\r\n");
      out.write("\t{type:'A2',name:'文化设施用地',colorno: 241},\r\n");
      out.write("\t{type:'A3',name:'教育科研用地',colorno: 21},\r\n");
      out.write("\t{type:'A4',name:'体育用地',colorno: 62},\r\n");
      out.write("\t{type:'A5',name:'医疗卫生用地',colorno: 11},\r\n");
      out.write("\t{type:'A6',name:'社会福利设施用地',colorno: 243},\r\n");
      out.write("\t{type:'A7',name:'文物古迹用地',colorno: 244},\r\n");
      out.write("\t{type:'A8',name:'外事用地',colorno: 230},\r\n");
      out.write("\t{type:'A9',name:'宗教设施用地',colorno: 232},\r\n");
      out.write("\t{type:'B',name:'商业服务业设施用地',colorno: 240},\r\n");
      out.write("\t{type:'B1',name:'商业设施用地',colorno: 240},\r\n");
      out.write("\t{type:'B2',name:'商务设施用地',colorno: 240},\r\n");
      out.write("\t{type:'B3',name:'娱乐康体用地',colorno: 240},\r\n");
      out.write("\t{type:'B4',name:'公用设施营业网点用地',colorno: 240},\r\n");
      out.write("\t{type:'B9',name:'其它服务设施用地',colorno: 240},\r\n");
      out.write("\t{type:'M',name:'工业用地',colorno: 35},\r\n");
      out.write("\t{type:'M1',name:'一类工业用地',colorno: 35},\r\n");
      out.write("\t{type:'M2',name:'二类工业用地',colorno: 37},\r\n");
      out.write("\t{type:'M3',name:'三类工业用地',colorno: 39},\r\n");
      out.write("\t{type:'W',name:'物流仓储用地',colorno: 193},\r\n");
      out.write("\t{type:'W1',name:'一类物流仓储用地',colorno: 193},\r\n");
      out.write("\t{type:'W2',name:'二类物流仓储用地',colorno: 195},\r\n");
      out.write("\t{type:'W3',name:'三类物流仓储用地',colorno: 197},\r\n");
      out.write("\t{type:'S',name:'交通设施用地',colorno: 8},\r\n");
      out.write("\t{type:'S1',name:'城市道路用地',colorno: 8},\r\n");
      out.write("\t{type:'S2',name:'轨道交通线路用地',colorno: 8},\r\n");
      out.write("\t{type:'S3',name:'综合交通枢纽用地',colorno: 8},\r\n");
      out.write("\t{type:'S4',name:'交通场站用地',colorno: 8},\r\n");
      out.write("\t{type:'S9',name:'其它交通设施用地',colorno: 8},\r\n");
      out.write("\t{type:'U',name:'公用设施用地',colorno: 154},\r\n");
      out.write("\t{type:'U1',name:'供应设施用地',colorno: 154},\r\n");
      out.write("\t{type:'U2',name:'环境设施用地',colorno: 136},\r\n");
      out.write("\t{type:'U3',name:'安全设施用地',colorno: 144},\r\n");
      out.write("\t{type:'U9',name:'其它公用设施用地',colorno: 147},\r\n");
      out.write("\t{type:'G',name:'绿地',colorno:90},\r\n");
      out.write("\t{type:'G1',name:'公园绿地',colorno:90},\r\n");
      out.write("\t{type:'G2',name:'防护绿地',colorno:104},\r\n");
      out.write("\t{type:'G3',name:'广场用地',colorno:93},\r\n");
      out.write("\t{type:'H1',name:'城乡居民点建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H11',name:'城市建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H12',name:'镇建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H13',name:'乡建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H14',name:'村庄建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H15',name:'独立建设用地',colorno: 0},\r\n");
      out.write("\t{type:'H2',name:'区域交通设施用地',colorno: 9},\r\n");
      out.write("\t{type:'H21',name:'铁路用地',colorno: 9},\r\n");
      out.write("\t{type:'H22',name:'公路用地',colorno: 9},\r\n");
      out.write("\t{type:'H23',name:'港口用地',colorno: 9},\r\n");
      out.write("\t{type:'H24',name:'机场用地',colorno: 9},\r\n");
      out.write("\t{type:'H25',name:'管道运输用地',colorno: 9},\r\n");
      out.write("\t{type:'H3',name:'区域公用设施用地',colorno: 156},\r\n");
      out.write("\t{type:'H4',name:'特殊用地',colorno:87},\r\n");
      out.write("\t{type:'H41',name:'军事用地',colorno:87},\r\n");
      out.write("\t{type:'H42',name:'安保用地',colorno:87},\r\n");
      out.write("\t{type:'H5',name:'采矿用地',colorno: 34},\r\n");
      out.write("\t{type:'E1',name:'水域',colorno:140},\r\n");
      out.write("\t{type:'E11',name:'自然水域',colorno:132},\r\n");
      out.write("\t{type:'E12',name:'水库',colorno:140},\r\n");
      out.write("\t{type:'E13',name:'坑塘沟渠',colorno:130},\r\n");
      out.write("\t{type:'E2',name:'农林用地',colorno: 82},\r\n");
      out.write("\t{type:'E3',name:'其它非建设用地',colorno:53},\r\n");
      out.write("\t{type:'E31',name:'空闲地',colorno:53},\r\n");
      out.write("\t{type:'E32',name:'其它非利用地',colorno:55}\r\n");
      out.write("];\r\n");
      out.write("\r\n");
      out.write("var colorIndexes=[\r\n");
      out.write("\t[0,0,0],[255,0,0],[255,255,0],[0,255,0],[0,255,255],[0,0,255],[255,0,255],[255,255,255],\r\n");
      out.write("\t[128,128,128],[192,192,192],[255,0,0],[255,127,127],[204,0,0],[204,102,102],[153,0,0],[153,76,76],\r\n");
      out.write("\t[127,0,0],[127,63,63],[76,0,0],[76,38,38],[255,63,0],[255,159,127],[204,51,0],[204,127,102],\r\n");
      out.write("\t[153,38,0],[153,95,76],[127,31,0],[127,79,63],[76,19,0],[76,47,38],[255,127,0],[255,191,127],\r\n");
      out.write("\t[204,102,0],[204,153,102],[153,76,0],[153,114,76],[127,63,0],[127,95,63],[76,38,0],[76,57,38],\r\n");
      out.write("\t[255,191,0],[255,223,127],[204,153,0],[204,178,102],[153,114,0],[153,133,76],[127,95,0],[127,111,63],\r\n");
      out.write("\t[76,57,0],[76,66,38],[255,255,0],[255,255,127],[204,204,0],[204,204,102],[153,153,0],[153,153,76],\r\n");
      out.write("\t[127,127,0],[127,127,63],[76,76,0],[76,76,38],[191,255,0],[223,255,127],[153,204,0],[178,204,102],\r\n");
      out.write("\t[114,153,0],[133,153,76],[95,127,0],[111,127,63],[57,76,0],[66,76,38],[127,255,0],[191,255,127],\r\n");
      out.write("\t[102,204,0],[153,204,102],[76,153,0],[114,153,76],[63,127,0],[95,127,63],[38,76,0],[57,76,38],\r\n");
      out.write("\t[63,255,0],[159,255,127],[51,204,0],[127,204,102],[38,153,0],[95,153,76],[31,127,0],[79,127,63],\r\n");
      out.write("\t[19,76,0],[47,76,38],[0,255,0],[127,255,127],[0,204,0],[102,204,102],[0,153,0],[76,153,76],\r\n");
      out.write("\t[0,127,0],[63,127,63],[0,76,0],[38,76,38],[0,255,63],[127,255,159],[0,204,51],[102,204,127],\r\n");
      out.write("\t[0,153,38],[76,153,95],[0,127,31],[63,127,79],[0,76,19],[38,76,47],[0,255,127],[127,255,191],\r\n");
      out.write("\t[0,204,102],[102,204,153],[0,153,76],[76,153,114],[0,127,63],[63,127,95],[0,76,38],[38,76,57],\r\n");
      out.write("\t[0,255,191],[127,255,223],[0,204,153],[102,204,178],[0,153,114],[76,153,133],[0,127,95],[63,127,111],\r\n");
      out.write("\t[0,76,57],[38,76,66],[0,255,255],[127,255,255],[0,204,204],[102,204,204],[0,153,153],[76,153,153],\r\n");
      out.write("\t[0,127,127],[63,127,127],[0,76,76],[38,76,76],[0,191,255],[127,223,255],[0,153,204],[102,178,204],\r\n");
      out.write("\t[0,114,153],[76,133,153],[0,95,127],[63,111,127],[0,57,76],[38,66,76],[0,127,255],[127,191,255],\r\n");
      out.write("\t[0,102,204],[102,153,204],[0,76,153],[76,114,153],[0,63,127],[63,95,127],[0,38,76],[38,57,76],\r\n");
      out.write("\t[0,63,255],[127,159,255],[0,51,204],[102,127,204],[0,38,153],[76,95,153],[0,31,127],[63,79,127],\r\n");
      out.write("\t[0,19,76],[38,47,76],[0,0,255],[127,127,255],[0,0,204],[102,102,204],[0,0,153],[76,76,153],\r\n");
      out.write("\t[0,0,127],[63,63,127],[0,0,76],[38,38,76],[63,0,255],[159,127,255],[51,0,204],[127,102,204],\r\n");
      out.write("\t[38,0,153],[95,76,153],[31,0,127],[79,63,127],[19,0,76],[47,38,76],[127,0,255],[191,127,255],\r\n");
      out.write("\t[102,0,204],[153,102,204],[76,0,153],[114,76,153],[63,0,127],[95,63,127],[38,0,76],[57,38,76],\r\n");
      out.write("\t[191,0,255],[223,127,255],[153,0,204],[178,102,204],[114,0,153],[133,76,153],[95,0,127],[111,63,127],\r\n");
      out.write("\t[57,0,76],[66,38,76],[255,0,255],[255,127,255],[204,0,204],[204,102,204],[153,0,153],[153,76,153],\r\n");
      out.write("\t[127,0,127],[127,63,127],[76,0,76],[76,38,76],[255,0,191],[255,127,223],[204,0,153],[204,102,178],\r\n");
      out.write("\t[153,0,114],[153,76,133],[127,0,95],[127,63,111],[76,0,57],[76,38,66],[255,0,127],[255,127,191],\r\n");
      out.write("\t[204,0,102],[204,102,153],[153,0,76],[153,76,114],[127,0,63],[127,63,95],[76,0,38],[76,38,57],\r\n");
      out.write("\t[255,0,63],[255,127,159],[204,0,51],[204,102,127],[153,0,38],[153,76,95],[127,0,31],[127,63,79],\r\n");
      out.write("\t[76,0,19],[76,38,47],[51,51,51],[91,91,91],[132,132,132],[173,173,173],[214,214,214],[255,255,255]\r\n");
      out.write("];\r\n");
      out.write("function intToHexString(v,len){\r\n");
      out.write("\tvar ret = v.toString(16);\r\n");
      out.write("\tif (ret.length < len){\r\n");
      out.write("\t\tvar a = len - ret.length;\r\n");
      out.write("\t\tfor(var i=0;i<a;i++){\r\n");
      out.write("\t\t\tret = '0' + ret;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn ret;\r\n");
      out.write("}\r\n");
      out.write("function getIndexColor(index){\r\n");
      out.write("    if (index < 0 || index >= colorIndexes.length){\r\n");
      out.write("    \treturn \"\";\r\n");
      out.write("    }\r\n");
      out.write("    var ret = '#';\r\n");
      out.write("    for(var i=0;i<3;i++){\r\n");
      out.write("    \tret += intToHexString(colorIndexes[index][i],2);\r\n");
      out.write("    }\r\n");
      out.write("    return ret;\r\n");
      out.write("}\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<title>测试页面</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<span>Type: </span><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${objType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<span>ID: </span><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${objID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<button onclick=\"ajaxData()\">Ajax获取数据</button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("function ajaxData(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlhead}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajax.html?ajax=test',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tdata: {'type':'类型','id':'12345'},\r\n");
      out.write("\t\ttimeout : 10000,\r\n");
      out.write("\t\tsuccess : function(msg, status) {\r\n");
      out.write("\t\t\tif (msg.status == 200) {\r\n");
      out.write("\t\t\t\tif (null != msg.rows){\r\n");
      out.write("\t\t\t\t\talert(\"get rows:\"+msg.rows.length);\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<msg.rows.length;i++){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(msg.rows[i]);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tshowError(msg.msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(){\r\n");
      out.write("\t\t\talert('网络访问失败！');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\t\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /backglobal.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("urlhead");
      // /backglobal.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
